pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - author=KEINOS
      - base=main
      - title~=^Changes
      - files=image_info.txt
      - check-success=Azure Scan / analysis
      - check-success=Snyk Scan / analysis
      - check-success=[container-scan] keinos/vscode-dev-container-go-test
    actions:
      merge:
        method: merge
