# Container analysis using Snyk.
# This workflow checks out the code, builds a container image using Docker and
# scans that image for vulnerabilities using Snyk.
name: Azure Scan

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  schedule:
    # Runs at 19:20 UTC on Sun (JST: AM 04:20 on every Monday)
    - cron: "20 19 * * SUN"

jobs:
  analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t keinos/vscode-dev-container-go-test .

      # Azure Container Scan scans the container with Dockle and Trivy.
      - name: Run Dockle and Trivy
        uses: Azure/container-scan@v0
        with:
          image-name: keinos/vscode-dev-container-go-test
          severity-threshold: CRITICAL
env:
  # See:
  #   https://github.com/goodwithtech/dockle/issues/188
  #   https://github.com/Azure/container-scan/issues/146
  DOCKLE_HOST: "unix:///var/run/docker.sock"
